name: Corenotes-web-cicd

on:
  push:
    branches: [ master ]

  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Use a GitHub Action
        #uses: actions/checkout@v3
        uses: appleboy/scp-action@master
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /corenotes-web
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            npm i
            npm run build
            npm run dev

      # - name: rsync deployments
      #   #uses: burnett01/rsync-deployments@5.1
      #   uses: appleboy/scp-action@master
      #   with:
      #     switches: -avzr --delete
      #     path: ./*
      #     remote_path: /corenotes-web
      #     remote_host: ${{ secrets.SSH_HOST }}
      #     remote_user: ${{ secrets.SSH_USER }}
      #     remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"